### ISSUE TITLE
`ServiceAccountKey` gives error `private_key: not a string` and never becomes ready after gcp-provider pod is restarted (for instance after a version upgrade)

### ISSUE THREAD

**Issue by jonnylangefeld** [upbound/provider-gcp#307]
### What happened?

We use the pattern of a `ServiceAccount` together with a `ServiceAccountKey` quite a lot, as suggested by the [examples](https://github.com/upbound/provider-gcp/blob/a74e05300b59c0e804ee241a974122bfad0b82d2/examples/cloudplatform/serviceaccountkey.yaml).

However, we recently upgraded `provider-gcp` from `v0.27.0` to `v.0.32.0`, which restarted the pod. After this process all our `ServiceAccountKey` resources got a condition like

```yaml
  - lastTransitionTime: "2023-05-20T00:59:13Z"
    message: 'observe failed: cannot get connection details: cannot get additional
      connection details: private_key: not a string'
    reason: ReconcileError
    status: "False"
    type: Synced
```

This gets all resources depending on `ServiceAccountKeys` into a non-ready state.

### How can we reproduce it?
1. Create a `ServiceAccount` and a `ServiceAccountKey` as suggested by the example:
https://github.com/upbound/provider-gcp/blob/a74e05300b59c0e804ee241a974122bfad0b82d2/examples/cloudplatform/serviceaccountkey.yaml#L1-L28

2. Wait for `ServiceAccountKey` to be synced and ready.

3. Restart the gcp-provider pod.

### What environment did it happen in?

* Crossplane Version: `v1.12.0`
* Provider Version: `v1.32.0`
* Kubernetes Version: `1.23`
* Kubernetes Distribution: GKE
