### ISSUE TITLE
GKE cluster  observation error when NodePool label is updated 

### ISSUE THREAD

**Issue by stevendborrelli** [upbound/provider-gcp#335]
### What happened?

Given a GKE cluster with a NodePool resource attached, a change in the labels of the NodePool will cause the GKE cluster to be stuck with the following error: 

```
 observe failed: cannot run plan: plan failed: Instance cannot be destroyed: Resource google_container_cluster.nodepool has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.
```

GCP added the ability to modify labels on a nodepool. This got merged into Terraform in this PR https://github.com/hashicorp/terraform-provider-google/pull/13284/files.

But as part of that PR https://github.com/hashicorp/terraform-provider-google/pull/13284/files#diff-fdebbacb7014a0b15201272d6e7806072b9dbecacc073dc11b2b59766e892bc6, on the cluster side it was set  that a label change would cause a recreation.

The NodeConfig is being populated into the Cluster Spec (probably via LateInit), which causes the issue:

```
 Node Config:
      Disk Size Gb:  100
      Disk Type:     pd-balanced
      Image Type:    COS_CONTAINERD
      Labels:
        key1:           value1-new
        key2:           value2
        key3:           value3
```

### How can we reproduce it?

Create a cluster using the following manifest:

```yaml
apiVersion: container.gcp.upbound.io/v1beta1
kind: NodePool
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1beta1/nodepool
  labels:
    testing.upbound.io/example-name: nodepool
  name: nodepool
spec:
  forProvider:
    autoscaling:
      - minNodeCount: 2
        maxNodeCount: 5
    clusterSelector:
      matchLabels:
        testing.upbound.io/example-name: nodepool
    nodeConfig:
    - machineType: e2-medium
      labels:
        key1: value1
        key2: value2
        key3: value3
      oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
      preemptible: true
      serviceAccountSelector:
        matchLabels:
          testing.upbound.io/example-name: nodepool
   #nodeCount: 1

---

apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1beta1/cluster
  labels:
    testing.upbound.io/example-name: nodepool
  name: nodepool
spec:
  forProvider:
    location: us-central1-a
    removeDefaultNodePool: true
    initialNodeCount: 1
---

apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1beta1/nodepool
  labels:
    testing.upbound.io/example-name: nodepool
  name: nodepool
spec:
  forProvider:
    displayName: Service Account for GKE Cluster
```

Wait for resources to be ready/synced:

```console
kubectl get managed 
NAME                                                   READY   SYNCED   EXTERNAL-NAME   AGE
serviceaccount.cloudplatform.gcp.upbound.io/nodepool   True    True     nodepool        11m

NAME                                        READY   SYNCED   EXTERNAL-NAME   AGE
cluster.container.gcp.upbound.io/nodepool   True    True     nodepool        11m

NAME                                         READY   SYNCED   EXTERNAL-NAME   AGE
nodepool.container.gcp.upbound.io/nodepool   False   True     nodepool        11m
```

To trigger the issue change/delete one of the labels on the NodePool and wait for reconciliation. 

The cluster will SYNCED status will be false:

```console
NAME                                                   READY   SYNCED   EXTERNAL-NAME   AGE
serviceaccount.cloudplatform.gcp.upbound.io/nodepool   True    True     nodepool        35m

NAME                                        READY   SYNCED   EXTERNAL-NAME   AGE
cluster.container.gcp.upbound.io/nodepool   True    False    nodepool        35m

NAME                                         READY   SYNCED   EXTERNAL-NAME   AGE
nodepool.container.gcp.upbound.io/nodepool   True    True     nodepool        35m
```

```console
 Warning  CannotObserveExternalResource  42s (x9 over 3m48s)  managed/container.gcp.upbound.io/v1beta1, kind=cluster  cannot run plan: plan failed: Instance cannot be destroyed: Resource google_container_cluster.nodepool has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.
```

Note that NodeConfig is populated in the cluster

```yaml
spec:
  deletionPolicy: Delete
  forProvider:
    addonsConfig:
    - gcePersistentDiskCsiDriverConfig:
      - enabled: true
    binaryAuthorization:
    - {}
    clusterAutoscaling:
    - {}
    databaseEncryption:
    - state: DECRYPTED
    defaultSnatStatus:
    - disabled: false
    initialNodeCount: 1
    location: us-central1-a
    loggingConfig:
    - enableComponents:
      - SYSTEM_COMPONENTS
      - WORKLOADS
    loggingService: logging.googleapis.com/kubernetes
    masterAuth:
    - clientCertificateConfig:
      - issueClientCertificate: false
    monitoringConfig:
    - enableComponents:
      - SYSTEM_COMPONENTS
    monitoringService: monitoring.googleapis.com/kubernetes
    network: projects/crossplane-playground/global/networks/default
    networkingMode: ROUTES
    nodeConfig:
    - diskSizeGb: 100
      diskType: pd-balanced
      imageType: COS_CONTAINERD
      labels:
        key1: value1-new
        key2: value2
        key3: value3
      loggingVariant: DEFAULT
      machineType: e2-medium
      metadata:
        disable-legacy-endpoints: "true"
      oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
      preemptible: true
      serviceAccount: nodepool@crossplane-playground.iam.gserviceaccount.com
      shieldedInstanceConfig:
      - enableIntegrityMonitoring: true
    nodePoolDefaults:
    - nodeConfigDefaults:
      - loggingVariant: DEFAULT
    notificationConfig:
    - pubsub:
      - enabled: false
    privateClusterConfig:
    - masterGlobalAccessConfig:
      - enabled: false
    project: crossplane-playground
    releaseChannel:
    - channel: REGULAR
    removeDefaultNodePool: true
    serviceExternalIpsConfig:
    - enabled: false
    subnetwork: projects/crossplane-playground/regions/us-central1/subnetworks/default
```

In terraform 4.73 we don't see the issue the `google_container_cluster`  `node_config` is updated with the new keys:

```hcl
       "node_config": [
              {
                "advanced_machine_features": [],
                "boot_disk_kms_key": "",
                "disk_size_gb": 100,
                "disk_type": "pd-balanced",
                "ephemeral_storage_local_ssd_config": [],
                "gcfs_config": [],
                "guest_accelerator": [],
                "gvnic": [],
                "image_type": "COS_CONTAINERD",
                "kubelet_config": [],
                "labels": {
                  "key1": "value1-new",
                  "key2": "value2",
                  "key3": "value3"
                },
```

### What environment did it happen in?

* Crossplane Version: UXP 1.12.2
* Provider Version: GCP Family Scoped v0.34.0
* Kubernetes Version: 1.27.1
* Kubernetes Distribution: Kind

**Comment by haarchri** [comment]
re-tested this problem 

in v0.32.0 i can see the following:
<img width="881" alt="image" src="https://github.com/upbound/provider-gcp/assets/21083497/5319bb5e-7e6d-4876-83a9-773d935e3d87">


in v0.34.0 everything looks good:

```
kubectl get managed | grep "gcp.upbound.io"                             
serviceaccount.cloudplatform.gcp.upbound.io/nodepool   True    True     nodepool        17m
cluster.container.gcp.upbound.io/nodepool   True    True     nodepool        17m
nodepool.container.gcp.upbound.io/nodepool   True    True     nodepool        17m
```


```
kubectl describe nodepool.container.gcp.upbound.io/nodepool 
Name:         nodepool
Namespace:    
Labels:       testing.upbound.io/example-name=nodepool
Annotations:  crossplane.io/external-create-pending: 2023-07-17T10:45:21Z
              crossplane.io/external-create-succeeded: 2023-07-17T10:45:21Z
              crossplane.io/external-name: nodepool
              meta.upbound.io/example-id: container/v1beta1/nodepool
              upjet.crossplane.io/provider-meta:
                {"e2bfb730-ecaa-11e6-8f88-34363bc7c4c0":{"create":1800000000000,"delete":1800000000000,"update":1800000000000},"schema_version":"1"}
API Version:  container.gcp.upbound.io/v1beta1
Kind:         NodePool
Metadata:
  Creation Timestamp:  2023-07-17T10:35:18Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:        5
  Resource Version:  545420
  UID:               f6e9550b-9af3-430e-9c3a-7d4076db1380
Spec:
  Deletion Policy:  Delete
  For Provider:
    Autoscaling:
      Max Node Count:  5
      Min Node Count:  2
    Cluster:           projects/crossplane-playground/locations/us-central1-a/clusters/nodepool
    Cluster Ref:
      Name:  nodepool
    Cluster Selector:
      Match Labels:
        testing.upbound.io/example-name:  nodepool
    Location:                             us-central1-a
    Management:
      Auto Repair:   true
      Auto Upgrade:  true
    Network Config:
    Node Config:
      Labels:
        key1:        value1-new
        key2:        value2
        key3:        value3
      Machine Type:  e2-medium
      Oauth Scopes:
        https://www.googleapis.com/auth/cloud-platform
      Preemptible:      true
      Service Account:  nodepool@crossplane-playground.iam.gserviceaccount.com
      Service Account Ref:
        Name:  nodepool
      Service Account Selector:
        Match Labels:
          testing.upbound.io/example-name:  nodepool
    Node Count:                             1
    Node Locations:
      us-central1-a
    Project:  crossplane-playground
    Upgrade Settings:
      Max Surge:      1
      Strategy:       SURGE
    Version:          1.26.5-gke.1200
  Management Policy:  FullControl
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
    Autoscaling:
      Location Policy:       ANY
      Max Node Count:        5
      Min Node Count:        2
      Total Max Node Count:  0
      Total Min Node Count:  0
    Cluster:                 projects/crossplane-playground/locations/us-central1-a/clusters/nodepool
    Id:                      projects/crossplane-playground/locations/us-central1-a/clusters/nodepool/nodePools/nodepool
    Initial Node Count:      0
    Instance Group Urls:
      https://www.googleapis.com/compute/v1/projects/crossplane-playground/zones/us-central1-a/instanceGroupManagers/gke-nodepool-nodepool-dbb4b519-grp
    Location:  us-central1-a
    Managed Instance Group Urls:
      https://www.googleapis.com/compute/v1/projects/crossplane-playground/zones/us-central1-a/instanceGroups/gke-nodepool-nodepool-dbb4b519-grp
    Management:
      Auto Repair:   true
      Auto Upgrade:  true
    Network Config:
      Create Pod Range:      false
      Enable Private Nodes:  false
      podIpv4CidrBlock:      
      Pod Range:             
    Node Config:
      Boot Disk Kms Key:  
      Disk Size Gb:       100
      Disk Type:          pd-balanced
      Image Type:         COS_CONTAINERD
      Labels:
        key1:           value1
        key2:           value2
        key3:           value3
      Local Ssd Count:  0
      Logging Variant:  DEFAULT
      Machine Type:     e2-medium
      Metadata:
        Disable - Legacy - Endpoints:  true
      Min Cpu Platform:                
      Node Group:                      
      Oauth Scopes:
        https://www.googleapis.com/auth/cloud-platform
      Preemptible:      true
      Service Account:  nodepool@crossplane-playground.iam.gserviceaccount.com
      Shielded Instance Config:
        Enable Integrity Monitoring:  true
        Enable Secure Boot:           false
      Spot:                           false
    Node Count:                       1
    Node Locations:
      us-central1-a
    Project:  crossplane-playground
    Upgrade Settings:
      Max Surge:        1
      Max Unavailable:  0
      Strategy:         SURGE
    Version:            1.26.5-gke.1200
  Conditions:
    Last Transition Time:  2023-07-17T10:45:21Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2023-07-17T10:49:32Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-07-17T10:49:22Z
    Reason:                Success
    Status:                True
    Type:                  LastAsyncOperation
    Last Transition Time:  2023-07-17T10:49:22Z
    Reason:                Finished
    Status:                True
    Type:                  AsyncOperation
Events:
  Type     Reason                           Age                 From                                                     Message
  ----     ------                           ----                ----                                                     -------
  Warning  CannotResolveResourceReferences  10m (x15 over 19m)  managed/container.gcp.upbound.io/v1beta1, kind=nodepool  cannot resolve references: mg.Spec.ForProvider.Cluster: referenced field was empty (referenced resource may not yet be ready)
  Normal   CreatedExternalResource          9m4s                managed/container.gcp.upbound.io/v1beta1, kind=nodepool  Successfully requested creation of external resource
  Warning  CannotObserveExternalResource    5m3s                managed/container.gcp.upbound.io/v1beta1, kind=nodepool  cannot run refresh: refresh failed:
  Warning  CannotUpdateManagedResource      4m59s               managed/container.gcp.upbound.io/v1beta1, kind=nodepool  Operation cannot be fulfilled on nodepools.container.gcp.upbound.io "nodepool": the object has been modified; please apply your changes to the latest version and try again
  Normal   UpdatedExternalResource          3m39s               managed/container.gcp.upbound.io/v1beta1, kind=nodepool  Successfully requested update of external resource
```

```
kubectl describe cluster.container.gcp.upbound.io/nodepool 
Name:         nodepool
Namespace:    
Labels:       testing.upbound.io/example-name=nodepool
Annotations:  crossplane.io/external-create-pending: 2023-07-17T10:35:34Z
              crossplane.io/external-create-succeeded: 2023-07-17T10:35:34Z
              crossplane.io/external-name: nodepool
              meta.upbound.io/example-id: container/v1beta1/cluster
              upjet.crossplane.io/provider-meta:
                {"e2bfb730-ecaa-11e6-8f88-34363bc7c4c0":{"create":2400000000000,"delete":2400000000000,"read":2400000000000,"update":3600000000000},"schem...
API Version:  container.gcp.upbound.io/v1beta1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2023-07-17T10:35:18Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:        2
  Resource Version:  544510
  UID:               48ccbbeb-1369-4946-bfb2-31bd4ff2768d
Spec:
  Deletion Policy:  Delete
  For Provider:
    Addons Config:
      Gce Persistent Disk Csi Driver Config:
        Enabled:  true
    Binary Authorization:
    Cluster Autoscaling:
    Database Encryption:
      State:  DECRYPTED
    Default Snat Status:
      Disabled:          false
    Initial Node Count:  1
    Location:            us-central1-a
    Logging Config:
      Enable Components:
        SYSTEM_COMPONENTS
        WORKLOADS
    Logging Service:  logging.googleapis.com/kubernetes
    Master Auth:
      Client Certificate Config:
        Issue Client Certificate:  false
    Monitoring Config:
      Enable Components:
        SYSTEM_COMPONENTS
    Monitoring Service:  monitoring.googleapis.com/kubernetes
    Network:             projects/crossplane-playground/global/networks/default
    Networking Mode:     ROUTES
    Node Pool Defaults:
      Node Config Defaults:
        Logging Variant:  DEFAULT
    Notification Config:
      Pubsub:
        Enabled:  false
    Private Cluster Config:
      Master Global Access Config:
        Enabled:  false
    Project:      crossplane-playground
    Release Channel:
      Channel:                 REGULAR
    Remove Default Node Pool:  true
    Service External Ips Config:
      Enabled:        false
    Subnetwork:       projects/crossplane-playground/regions/us-central1/subnetworks/default
  Management Policy:  FullControl
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
    Addons Config:
      Gce Persistent Disk Csi Driver Config:
        Enabled:  true
      Network Policy Config:
        Disabled:  true
    Binary Authorization:
      Enabled:          false
      Evaluation Mode:  
    Cluster Autoscaling:
      Enabled:        false
    clusterIpv4Cidr:  10.96.0.0/14
    Database Encryption:
      Key Name:         
      State:            DECRYPTED
    Datapath Provider:  
    Default Snat Status:
      Disabled:                   false
    Description:                  
    Enable Autopilot:             false
    Enable Binary Authorization:  false
    Enable Intranode Visibility:  false
    Enable Kubernetes Alpha:      false
    enableL4IlbSubsetting:        false
    Enable Legacy Abac:           false
    Enable Shielded Nodes:        true
    Enable Tpu:                   false
    Endpoint:                     34.170.225.151
    Id:                           projects/crossplane-playground/locations/us-central1-a/clusters/nodepool
    Initial Node Count:           1
    Label Fingerprint:            a9dc16a7
    Location:                     us-central1-a
    Logging Config:
      Enable Components:
        SYSTEM_COMPONENTS
        WORKLOADS
    Logging Service:  logging.googleapis.com/kubernetes
    Master Auth:
      Client Certificate:  
      Client Certificate Config:
        Issue Client Certificate:  false
      Cluster Ca Certificate:      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRWmNvaVV3ejR0SlFYeFBDank0U3VCVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSak1USTVZbVEyTnkwNU9EZzJMVFJoWW1VdE9HSTBNaTFtWVdReE9EZzNOakF5WkdVdwpJQmNOTWpNd056RTNNRGt6TlRNNFdoZ1BNakExTXpBM01Ea3hNRE0xTXpoYU1DOHhMVEFyQmdOVkJBTVRKR014Ck1qbGlaRFkzTFRrNE9EWXROR0ZpWlMwNFlqUXlMV1poWkRFNE9EYzJNREprWlRDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU14Q0IxQVNQUm1nUWwycEM1MVo1WkFKRk5kajNtU1Nvdkx0bXdxOQpoUWo3Q0Nzbk9uR2NnQVdUcExZSkZOczNNUGJwQTB6dCtHM2pHRWxvekpmWS9PQmY2MnFjV0Z6RytXTW16aVFHCnNWeFNiOFhVbFZQNzJGM0ptOGxOU1grandBSVgrci9tdUQ4L21VTzQ0RG1LTGZDQldHSjJFV2IwUERvQWNhMjEKbWhGVHhCM1RQdlcxNmNMdTFTMXdrNnpNQzNjMTZxK3ZJUmIycWhMMDdVSS9keHZXZTd3R1h1U0lSNjZPbmcyTApzMjB0YnRZMTdpSFdmOWg0c0Qyb1VCbkMvR3R3d0FvSHVadnJGMFVzYkpIa0lxR01JUG9Ra0dBMDhyM3kwMTJQCloxV1BCRm5Ba1QzNUJCUUxaMFZUUmk0UmFrUHoxNURqbk1yb1F6TWxLOHJab1lXdkdmMG9TUlhmYmdqQ2VPb3QKeFI4MThMaVpUMlIvL050SVBxTHRZYVFFV1dyQ045d1dMN3ZrdmtXN05vbjd4OHJqaGtEVktGMUNHMkhXUllZYgpUVmVLN2lYT2czaHJkUm0vSzErSWdwMUdrVGdhd01lajIwU2dSQzRqcVRkSGNWTEtqMGtkUDkrRVh6bnRNM0NXCjArNElIZGtKV2w0SFp1dlFsOVI5anppMEt3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUxbXZSeWpDSnZ5YU12dHJ4bTNkNHI4cldlTmN3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFHd2NWbWwzYmk4K2U4eXpHbmNaNW5wMkd6bnFYemttdTZBeU9rVlVQL05TCnBXMXVWVGVscTdFREZvQW83YnpHZVZlSmtaTjFRSzJnbkJtSHlFamN6SG41ajlMc3JwSTZiTDM5UGE0YXVXa0kKZWZNNjVGdWQycUVWdXFyakVzTmg0d2RaUGd3NzBzZ09LMmRoYTYwOHlVYkhEdGh2OUtMeDZNdG5kYndKcXcrMQpISXRlbFBqTHIxbElPY0Yyd2xVbDVHMmNMbkY1dzhxbXg0aUVIa05pcnB3V3hsK0JlYkJIbUNmNGk0bzRFeTBUCjdWTHhFVWs1cU93UFpQdTJDSTJVTmxEZWgwcks2bEJlenl6VjlrUlRwRyttaUVxTGwraFpNbXE5R1lzMnYzYnkKOTdHeWM2eVp1MWczdmFqRU5nVHVWdXFqZnJzSzZseEhUcVZYUWFzYzE3YWYwb1BpREpDS2wwTmpnYm9kUVVsNApGQVNVeE0rVE1YUkxpcnJhdVZXUDh5ZlZ5Mk5QaGl0OGlyZjRsVEVxbVA4Yy8vMVN0L2x0TVVwTkRhTkdJOFlrCkZMVHh1SThKcG5ZZ2s0R3g1Q0E3Z1V1eSszYTlWelJORldEMHdUdTB3UE1pZkorREdwcVhES3JkTDRzOXBrV3QKNENCQWNPVFZGdG1Bak9wYVRwOUpHUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    Master Version:                1.26.5-gke.1200
    Monitoring Config:
      Enable Components:
        SYSTEM_COMPONENTS
    Monitoring Service:  monitoring.googleapis.com/kubernetes
    Network:             projects/crossplane-playground/global/networks/default
    Network Policy:
      Enabled:        false
      Provider:       PROVIDER_UNSPECIFIED
    Networking Mode:  ROUTES
    Node Pool Defaults:
      Node Config Defaults:
        Logging Variant:  DEFAULT
    Node Version:         1.26.5-gke.1200
    Notification Config:
      Pubsub:
        Enabled:  false
        Topic:    
    Private Cluster Config:
      Enable Private Endpoint:  false
      Enable Private Nodes:     false
      Master Global Access Config:
        Enabled:                    false
      masterIpv4CidrBlock:          
      Peering Name:                 
      Private Endpoint:             10.128.0.42
      Private Endpoint Subnetwork:  
      Public Endpoint:              34.170.225.151
    privateIpv6GoogleAccess:        
    Project:                        crossplane-playground
    Release Channel:
      Channel:                 REGULAR
    Remove Default Node Pool:  true
    Self Link:                 https://container.googleapis.com/v1/projects/crossplane-playground/zones/us-central1-a/clusters/nodepool
    Service External Ips Config:
      Enabled:         false
    servicesIpv4Cidr:  10.99.240.0/20
    Subnetwork:        projects/crossplane-playground/regions/us-central1/subnetworks/default
    tpuIpv4CidrBlock:  
  Conditions:
    Last Transition Time:  2023-07-17T10:35:34Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2023-07-17T10:44:49Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-07-17T10:44:44Z
    Reason:                Success
    Status:                True
    Type:                  LastAsyncOperation
    Last Transition Time:  2023-07-17T10:44:44Z
    Reason:                Finished
    Status:                True
    Type:                  AsyncOperation
Events:
  Type     Reason                         Age                From                                                    Message
  ----     ------                         ----               ----                                                    -------
  Warning  CannotConnectToProvider        19m (x4 over 19m)  managed/container.gcp.upbound.io/v1beta1, kind=cluster  cannot get terraform setup: cannot get referenced ProviderConfig: ProviderConfig.gcp.upbound.io "default" not found
  Normal   CreatedExternalResource        19m                managed/container.gcp.upbound.io/v1beta1, kind=cluster  Successfully requested creation of external resource
  Warning  CannotObserveExternalResource  10m                managed/container.gcp.upbound.io/v1beta1, kind=cluster  cannot run refresh: refresh failed:
  Warning  CannotUpdateManagedResource    10m                managed/container.gcp.upbound.io/v1beta1, kind=cluster  Operation cannot be fulfilled on clusters.container.gcp.upbound.io "nodepool": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by haarchri** [comment]
if i want to delete an key i can reproduce this issue as well in v0.34.0:

```
kubectl get managed | grep "gcp.upbound.io"                
serviceaccount.cloudplatform.gcp.upbound.io/nodepool   True    True     nodepool        31m
cluster.container.gcp.upbound.io/nodepool   True    False    nodepool        31m
nodepool.container.gcp.upbound.io/nodepool   True    True     nodepool        31m
```

**Comment by turkenf** [comment]
Hi folks,

I am facing this issue in provider-gcp v0.34.0 in both cases(change/delete) when I change the `key1`, conditions for `container.Cluster` resource:
```
  conditions:
  - lastTransitionTime: "2023-07-17T14:04:11Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-07-17T14:34:29Z"
    message: 'observe failed: cannot run plan: plan failed: Instance cannot be destroyed:
      Resource google_container_cluster.nodepool has lifecycle.prevent_destroy set,
      but the plan calls for this resource to be destroyed. To avoid this error and
      continue with the plan, either disable lifecycle.prevent_destroy or reduce the
      scope of the plan using the -target flag.'
    reason: ReconcileError
    status: "False"
    type: Synced
  - lastTransitionTime: "2023-07-17T14:04:02Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
  - lastTransitionTime: "2023-07-17T14:04:02Z"
    reason: Finished
    status: "True"
    type: AsyncOperation
```

In case the terraform version is upgraded to 4.73.0, changing the value of `key1` does not cause an error and it updates successfully, but when we delete one of the labels, we continue to get the same error.
