### ISSUE TITLE
ProjectSink project does not work correctly when OIDC is in use

### ISSUE THREAD

**Issue by stevendborrelli** [upbound/provider-gcp#351]
### What happened?

*Note: this only happens with OIDC credentials, not with a static json file.*

When creating a ProjectSink in a separate project than the ProviderConfig, you will get an error similar to the following, because the provider is doing an `Observe` on the project from the providerConfig, and not from the `project` field on the MR. 

```
- lastTransitionTime: "2023-08-08T16:14:37Z"
    message: 'apply failed: googleapi: Error 409: Sink test-pubsublogsink-xtlh6-zvff7
      already exists, alreadyExists: '
    reason: ApplyFailure
    status: "False"
    type: LastAsyncOperation
``` 

### How can we reproduce it?

Create a providerConfig using OIDC, uses a project `project-a`. And use the following composition:

definition.yaml
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpubsublogsinks.it.example.com
spec:
  group: it.example.com
  names:
    kind: XPubSubLogSink
    plural: xpubsublogsinks
  claimNames:
    kind: PubSubLogSink
    plural: pubsublogsinks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      additionalPrinterColumns:
        - jsonPath: .spec.parameters.sourceProject
          name: SOURCE_GCP_PROJECT
          type: string
        - jsonPath: .status.subscriptionId
          name: SUBSCRIPTION_ID
          type: string
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    deletionPolicy:
                      description: |
                        When the Composition is deleted, Delete will remove the resources from GCP. Orphan
                        will not remove the resource from the Cloud. Default is Delete.
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    providerConfigName:
                      description: Upbound ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                    sourceProject:
                      description: Name of the GCP Project from which logs will be forwarded
                      type: string
                    logFilter:
                      description: The log filter to use for the sink
                      type: string
                  required:
                    - sourceProject
                    - logFilter
              required:
                - parameters
            status:
              type: object
              properties:
                topicId:
                  type: string
                  description: Topic identifier with format projects/{{project}}/topics/{{name}}
                sinkWriterIdentity:
                  type: string
                  description: The identity associated with the sink
                subscriptionId:
                  type: string
                  description: ID of the Project Sink Subscription
```

composition.yaml
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpubsublogsink.it.example.com
  labels:
    crossplane.io/provider: gcp
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: it.example.com/v1alpha1
    kind: XPubSubLogSink
  patchSets:
    - name: providerConfigRef
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.providerConfigRef.name
    - name: deletionPolicy
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
  resources:
    - name: pub-sub-topic
      base:
        apiVersion: pubsub.gcp.upbound.io/v1beta1
        kind: Topic
        spec:
          forProvider: {}
      patches:
        - type: PatchSet
          patchSetName: providerConfigRef
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.topicId

    - name: project-log-sink
      base:
        apiVersion: logging.gcp.upbound.io/v1beta1
        kind: ProjectSink
        spec:
          forProvider:
            uniqueWriterIdentity: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: status.topicId
          toFieldPath: spec.forProvider.destination
          transforms:
            - type: string
              string:
                fmt: "pubsub.googleapis.com/%s"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.logFilter
          toFieldPath: spec.forProvider.filter
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.sourceProject
          toFieldPath: spec.forProvider.project
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.writerIdentity
          toFieldPath: status.sinkWriterIdentity
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.subscriptionId

    - name: topic-subscription
      base:
        apiVersion: pubsub.gcp.upbound.io/v1beta1
        kind: Subscription
        spec:
          forProvider:
            topicSelector:
              matchControllerRef: true

    - name: topic-iam-member
      base:
        apiVersion: pubsub.gcp.upbound.io/v1beta1
        kind: TopicIAMMember
        spec:
          forProvider:
            role: roles/pubsub.publisher
            topicSelector:
              matchControllerRef: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: status.sinkWriterIdentity
          toFieldPath: spec.forProvider.member
```

XR Manifest
```yaml
apiVersion: it.example.com/v1alpha1
kind: PubSubLogSink
metadata:
  name: test-pubsublogsink
  namespace: default
spec:
  parameters:
    sourceProject: project-b
    #logFilter: |
    #  resource.type="audited_resource"
    logFilter: |
      logName:"cloudaudit.googleapis.com" OR
      log_id("compute.googleapis.com/firewall") OR
      log_id("threatdetection.googleapis.com/detection") 
```

### What environment did it happen in?

* Crossplane Version: 1.12.2
* Provider Version: v0.35.0
* Kubernetes Version:  Upbound Cloud
* Kubernetes Distribution:  Upbound Cloud
