### ISSUE TITLE
GKE Cluster CannotObserveExternalResource | provider-gcp v0.35.0

### ISSUE THREAD

**Issue by nzacharia** [upbound/provider-gcp#359]
### What happened?

I tried to create a GKE cluster and when the cluster managed resources deployed then im getting the following error :

```bash
Warning  CannotObserveExternalResource  17s (x4 over 7m14s)  managed/container.gcp.upbound.io/v1beta1, kind=cluster  cannot run refresh: refresh failed: Missing required argument: The argument "enabled" is required, but no definition was found.
Missing required argument: The argument "disabled" is required, but no definition was found.
Missing required argument: The argument "enabled" is required, but no definition was found.
Missing required argument: The argument "issue_client_certificate" is required, but no definition was found.
Missing required argument: The argument "enabled" is required, but no definition was found.
```

Note: the cluster on GCP console looks healthy

### How can we reproduce it?

Use provider-gcp:v0.35.0 or provider-gcp:v0.34.0 and try to create the following:

```yaml
apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1beta1/cluster
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    enableAutopilot: true
    ipAllocationPolicy:
      - {}
    location: europe-north1
```

### What environment did it happen in?

* Crossplane Version: crossplane-stable
* Provider Version: provider-gcp:v0.35.0 or provider-gcp:v0.35.0
* Kubernetes Version: Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
* Kubernetes Distribution:GKE
