### ISSUE TITLE
DatabaseInstance replica configuration required for non-mysql instances

### ISSUE THREAD

**Issue by snelsondexcom** [upbound/provider-gcp#379]
### What happened?

Per the docs, `replicaConfiguration` should only be applicable to MySQL instances:
> Valid only for MySQL instances

I was able to create a read replica for a PostgreSQL CloudSQL instance using the `DatabaseInstance` resource but it failed to sync with the following error:
```
"error": "cannot run refresh: refresh failed: Missing required argument: \"replica_configuration.0.master_heartbeat_period\" ...
```
Workaround to get the refresh to succeed -- provide an "empty" replica config, e.g.
```
    replicaConfiguration:
    - clientCertificate: ""
      clientKey: ""
      connectRetryInterval: 0
      dumpFilePath: ""
      failoverTarget: false
      masterHeartbeatPeriod: 0
      sslCipher: ""
      username: ""
      verifyServerCertificate: false
```

### How can we reproduce it?

Create a read replica for a PostgreSQL CloudSQL instance.

### What environment did it happen in?

* Crossplane Version: v1.10.2
* Provider Version: v0.35.1
* Kubernetes Version: v1.28.1
* Kubernetes Distribution: GKE
