### ISSUE TITLE
[provider-Redis] writeConnectionSecretToRef doesn't publish ip address

### ISSUE THREAD

**Issue by stephaneetje** [upbound/provider-gcp#387]
Hello,
After deploying a redis server with the following: 
```
apiVersion: redis.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  name: redis-loadtest-cc
spec:
  providerConfigRef:
    name: unbound-provider-config-gcp
  forProvider:
    authEnabled: true
    labels:
      environment: loadtest
      platform: loadtest-cc
    memorySizeGb: 1
    region: europe-west1
    tier: BASIC
    redisVersion: REDIS_4_0
  writeConnectionSecretToRef:
    namespace: test
    name: redis-loadtest-cc
```

i can't get the IP adress with `writeConnectionSecretToRef`, i only get attribute.auth_string :

```
$ k describe secret redis-loadtest-cc
Name:         redis-loadtest-cc
Namespace:    test
Labels:       <none>
Annotations:  <none>

Type:  connection.crossplane.io/v1alpha1

Data
====
attribute.auth_string:  36 bytes
```

Can we add that information to the output ?
