### ISSUE TITLE
Unable to create Topic with legal characters in the name like `.`

### ISSUE THREAD

**Issue by scheuk** [upbound/provider-gcp#402]
### What happened?
I attempted to create a pubsub topic name with a legal character in it. 
and when attempting to reconcile I receive this error:

```
  - lastTransitionTime: "2023-09-29T12:59:46Z"
    message: 'observe failed: cannot run refresh: refresh failed: Invalid resource
      name: A name must start with a letter or underscore and may contain only letters,
      digits, underscores, and dashes.'
    reason: ReconcileError
    status: "False"
    type: Synced
```

### How can we reproduce it?
create a test topic with `.` in the name
```
apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Topic
metadata:
  name: topic.name
spec:
  forProvider: {}
  providerConfigRef:
    name: providerconfig
```

Here' is the resource naming rules for pubsub topics: 
https://cloud.google.com/pubsub/docs/pubsub-basics#resource_names

### What environment did it happen in?

* Crossplane Version: 1.13.2
* Provider Version: v0.36.0
* Kubernetes Version: v1.27.3
* Kubernetes Distribution: GKE
