### ISSUE TITLE
BackendService: allow using InstanceGroup in groupRef and groupSelector

### ISSUE THREAD

**Issue by selfuryon** [upbound/provider-gcp#417]
### What problem are you facing?
I found that that in `BackendService` I have three parameteres for configution backends:
* [group](https://marketplace.upbound.io/providers/upbound/provider-gcp-compute/v0.38.0/resources/compute.gcp.upbound.io/BackendService/v1beta1#doc:spec-forProvider-backend-group)
* [groupRef](https://marketplace.upbound.io/providers/upbound/provider-gcp-compute/v0.38.0/resources/compute.gcp.upbound.io/BackendService/v1beta1#doc:spec-forProvider-backend-groupRef)
* [groupSelector](https://marketplace.upbound.io/providers/upbound/provider-gcp-compute/v0.38.0/resources/compute.gcp.upbound.io/BackendService/v1beta1#doc:spec-forProvider-backend-groupSelector)

But turns out that I can't use `InstanceGroup` objects in `groupRef` and `groupSelector`: they are binded to `InstanceGroupManager`

### How could Official GCP Provider help solve your problem?

Allow to use `InstanceGroup` in `groupRef` and `groupSelector` options.

**Comment by turkenf** [comment]
@selfuryon, thank you for raising this.

The common usage for the `backend.group` [parameter](https://registry.terraform.io/providers/hashicorp/google/3.77.0/docs/resources/compute_backend_service#group:~:text=create%20the%20resource.-,group,-%2D%20(Required)%20The%20fully) seems to be the URL of the Instance Group resource.

**Comment by selfuryon** [comment]
@turkenf Sorry, your link is broken. You wanted to point out [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service#group)? The problem here is that I need to specify fully-qualified URL for specifying instance groups. It looks like that:

```yaml
spec:
  forProvider:
    protocol: TCP
    portName: api-server
    timeoutSec: 5
    healthChecksRefs:
      - name: api-server
    backend:
      - group: https://www.googleapis.com/compute/v1/projects/***/zones/europe-west1-b/instanceGroups/group1
      - group: https://www.googleapis.com/compute/v1/projects/***/zones/europe-west3-b/instanceGroups/group2
      - group: https://www.googleapis.com/compute/v1/projects/***/zones/europe-west4-b/instanceGroups/group3
  providerConfigRef:
    name: ***
metadata:
  name: ***-api-server
  namespace: crossplane-system
kind: BackendService
apiVersion: compute.gcp.upbound.io/v1beta1

```
From my perspective, crossplane provides a solution for that by using an additional field for cross-referencing like `groupRef` or/and `groupSelector` usually in all resources, for example like in TcpProxy for referencing backend service:

```yaml
spec:
  forProvider:
    backendServiceRef:
      name: api-server
  providerConfigRef:
    name: ***
metadata:
  name: api-server
  namespace: crossplane-system
kind: TargetTCPProxy
apiVersion: compute.gcp.upbound.io/v1beta1
```
I still can use raw [forProvider.backendService](https://marketplace.upbound.io/providers/upbound/provider-gcp-compute/v0.38.0/resources/compute.gcp.upbound.io/TargetTCPProxy/v1beta1#doc:spec-forProvider-backendService), but crossplane allows me to reduce my pain and fill a full url by itself, I need only specify a crossplane resource for that.

The problem here that `backend.group` in `BackendService` can point out to different resource types, and related `groupRef` and `groupSelector` can refers **only** `InstanceGroupManager`. 

I don't know, is it possible to add some dual logic in checking resource types and add possibility to `groupRef` to have a link to `InstanceGroup` too? Maybe you can show me where is that code, I didn't find that, sorry =\
