### ISSUE TITLE
gcp.secretVersion: error response from GCP API

### ISSUE THREAD

**Issue by natereid72** [upbound/provider-gcp#45]
### What happened?

https://marketplace.upbound.io/providers/upbound/provider-gcp/v0.17.0/resources/secretmanager.gcp.upbound.io/SecretVersion/v1beta1

When secretVersion attempts to create, I receive this error:

```console
Conditions:
    Last Transition Time:  2022-11-09T20:23:19Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
    Last Transition Time:  2022-11-09T20:23:19Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-11-09T20:23:57Z
    Reason:                Finished
    Status:                True
    Type:                  AsyncOperation
    Last Transition Time:  2022-11-09T20:23:20Z
    Message:               apply failed: Error creating SecretVersion: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1/test:addVersion?alt=json</code> was not found on this server.  <ins>That’s all we know.</ins>
: 
    Reason:  ApplyFailure
    Status:  False
    Type:    LastAsyncOperation
```

### How can we reproduce it?

Try doing what I did above.

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: secretmanager/v1beta1/secretversion
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: default
type: Opaque
stringData:
  secret: "test"
---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretVersion
metadata:
  annotations:
    meta.upbound.io/example-id: secretmanager/v1beta1/secretversion
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    secretDataSecretRef:
      key: secret
      name: test
      namespace: default
    secretSelector:
      matchLabels:
        testing.upbound.io/example-name: test
---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: secretmanager/v1beta1/secretversion
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    labels:
      environment: dev
    replication:
      - automatic: true
```  

### What environment did it happen in?

UXP v1.10.1-up.1
provider-gcp v0.17.0
K8a v1.25.0
